extensions:
  pprof: {}

receivers:
  otlp:
    protocols:
      grpc: {}

exporters:
  nop:
  otlp:
    endpoint: otlp.example.com:4317
    sending_queue:
      enabled: true
      queue_size: 1000
    batch:
      flush_timeout: 200ms
      min_size: 8192
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  otlphttp:
    endpoint: https://otlp.example.com/otlp
    sending_queue:
      enabled: true
      queue_size: 1000
    batch:
      flush_timeout: 200ms
      min_size: 8192
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  extensions: [ pprof ]
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: []
      exporters:  [ nop, otlp, otlphttp ]
